package resolv_test

import (
	"testing"

	"github.com/jhford/openvpn-up/pkg"
	"github.com/stretchr/testify/assert"

	"github.com/jhford/openvpn-up/pkg/resolv"
)

func TestGenerateFile(t *testing.T) {
	tests := []struct {
		input    resolv.Config
		expected []byte
	}{
		{
			input: resolv.Config{
				NameServers: []pkg.NameServer{{127, 0, 0, 1}},
			},
			expected: []byte("# generated by openvpn-up 0.0.0-0000000\nnameserver 127.0.0.1\n"),
		},
	}

	for _, test := range tests {
		test := test

		actual := test.input.GenerateFile()

		assert.Equal(t, test.expected, actual)
	}
}
