package resolv

import (
	"bytes"
	"fmt"
	"net"

	"github.com/jhford/openvpn-up/pkg"
)

// Config is resolve writer configuration
type Config struct {
	NameServers []pkg.NameServer
}

// GenerateFile generates the contents of a file
func (c Config) GenerateFile() []byte {
	var output bytes.Buffer

	_, err := fmt.Fprintf(&output, "# generated by %s %s-%s\n", pkg.Name, pkg.Version, pkg.Commit)
	if err != nil {
		panic(err)
	}

	for _, ns := range c.NameServers {
		_, err = fmt.Fprintf(&output, "nameserver %s\n", net.IP(ns).String())
		if err != nil {
			panic(err)
		}
	}

	return output.Bytes()
}
