package resolv

import (
	"bytes"
	"fmt"
	"net"

	"github.com/jhford/openvpn-helper/pkg"
)

// Config is resolve writer configuration
type Config struct {
	NameServers []pkg.NameServer
	Output      string
}

// GenerateFile generates the contents of a file
func (c Config) GenerateFile() []byte {
	var output bytes.Buffer

	fmt.Fprintf(&output, "# generated by openvpn-helper\n")

	for _, ns := range c.NameServers {
		fmt.Fprintf(&output, "nameserver %s\n", net.IP(ns).String())
	}

	return output.Bytes()
}

// Apply applies a configuration
func (c Config) Apply() error {

	return nil
}
